package Vista;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.HierarchyEvent;
import java.awt.event.HierarchyListener;
import java.io.File;
import java.net.MalformedURLException; // Importación necesaria para URL

public class Vista_LeccionSALUDOS extends JPanel {

    public Vista_LeccionSALUDOS() {
        initComponents();

    }
    
  
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCOMPLETOSALUDOS = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelImagen1Saludos = new javax.swing.JLabel();
        jLabelImagen2Saludos = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaTexto1Saludos = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaTexto2Saludos = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCOMPLETOSALUDOS.setText("SIGUIENTE");
        add(jButtonCOMPLETOSALUDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, 180, 70));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Saludos");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 70, 40));

        jLabelImagen1Saludos.setText("jLabel2");
        add(jLabelImagen1Saludos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 260, 220));

        jLabelImagen2Saludos.setText("jLabel2");
        add(jLabelImagen2Saludos, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 290, 260));

        jTextAreaTexto1Saludos.setColumns(20);
        jTextAreaTexto1Saludos.setLineWrap(true);
        jTextAreaTexto1Saludos.setRows(5);
        jTextAreaTexto1Saludos.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextAreaTexto1Saludos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 280, 240));

        jTextAreaTexto2Saludos.setColumns(20);
        jTextAreaTexto2Saludos.setLineWrap(true);
        jTextAreaTexto2Saludos.setRows(5);
        jTextAreaTexto2Saludos.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaTexto2Saludos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 130, 330, 260));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonCOMPLETOSALUDOS;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelImagen1Saludos;
    public javax.swing.JLabel jLabelImagen2Saludos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextArea jTextAreaTexto1Saludos;
    public javax.swing.JTextArea jTextAreaTexto2Saludos;
    // End of variables declaration//GEN-END:variables
}
