/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Jhony Espinoza
 */
public class Vista_Unidad1 extends javax.swing.JPanel {

    /**
     * Creates new form Vista_Unidad1
     */
    public Vista_Unidad1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBarUNIDAD1 = new javax.swing.JProgressBar();
        jButtonFINALIZARUNIDAD1 = new javax.swing.JButton();
        jButtonLECCIONSALUDOS = new javax.swing.JButton();
        jButtonLECCIONFONOLOGIA = new javax.swing.JButton();
        jButtonLECCIONPRONOMBRES = new javax.swing.JButton();
        jButtonACTIIVIDAD1 = new javax.swing.JButton();
        jButtonEVALUACION = new javax.swing.JButton();
        jButtonACTIVIDAD2 = new javax.swing.JButton();
        jButtonREINICIARU1 = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1190, 660));
        setMinimumSize(new java.awt.Dimension(1190, 660));
        setPreferredSize(new java.awt.Dimension(1190, 660));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBarUNIDAD1.setBackground(new java.awt.Color(204, 204, 204));
        jProgressBarUNIDAD1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jProgressBarUNIDAD1.setForeground(new java.awt.Color(0, 204, 204));
        jProgressBarUNIDAD1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jProgressBarUNIDAD1.setStringPainted(true);
        add(jProgressBarUNIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 260, 30));

        jButtonFINALIZARUNIDAD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/BtnFinalizarU1.png"))); // NOI18N
        add(jButtonFINALIZARUNIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 600, 200, 40));

        jButtonLECCIONSALUDOS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/SaludosUnidad1.png"))); // NOI18N
        jButtonLECCIONSALUDOS.setMaximumSize(new java.awt.Dimension(80, 20));
        jButtonLECCIONSALUDOS.setMinimumSize(new java.awt.Dimension(80, 20));
        jButtonLECCIONSALUDOS.setPreferredSize(new java.awt.Dimension(80, 20));
        add(jButtonLECCIONSALUDOS, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 70));

        jButtonLECCIONFONOLOGIA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fonologia.png"))); // NOI18N
        jButtonLECCIONFONOLOGIA.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jButtonLECCIONFONOLOGIA.setMaximumSize(new java.awt.Dimension(120, 70));
        jButtonLECCIONFONOLOGIA.setMinimumSize(new java.awt.Dimension(120, 70));
        jButtonLECCIONFONOLOGIA.setPreferredSize(new java.awt.Dimension(120, 70));
        add(jButtonLECCIONFONOLOGIA, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 120, 70));

        jButtonLECCIONPRONOMBRES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/PronombresU1.png"))); // NOI18N
        add(jButtonLECCIONPRONOMBRES, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 120, 70));

        jButtonACTIIVIDAD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ActividadU1.png"))); // NOI18N
        add(jButtonACTIIVIDAD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 120, 70));

        jButtonEVALUACION.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EvaluacionU1.png"))); // NOI18N
        add(jButtonEVALUACION, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 450, 120, 70));

        jButtonACTIVIDAD2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ActividadU1.png"))); // NOI18N
        jButtonACTIVIDAD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonACTIVIDAD2ActionPerformed(evt);
            }
        });
        add(jButtonACTIVIDAD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 260, 120, 70));

        jButtonREINICIARU1.setText("Reiniciar");
        add(jButtonREINICIARU1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 60, 100, 50));

        jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Flechaback.png"))); // NOI18N
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        add(jButtonBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 590, 150, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoUnidad1.jpg"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonACTIVIDAD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonACTIVIDAD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonACTIVIDAD2ActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Fondo;
    public javax.swing.JButton jButtonACTIIVIDAD1;
    public javax.swing.JButton jButtonACTIVIDAD2;
    public javax.swing.JButton jButtonBack;
    public javax.swing.JButton jButtonEVALUACION;
    public javax.swing.JButton jButtonFINALIZARUNIDAD1;
    public javax.swing.JButton jButtonLECCIONFONOLOGIA;
    public javax.swing.JButton jButtonLECCIONPRONOMBRES;
    public javax.swing.JButton jButtonLECCIONSALUDOS;
    public javax.swing.JButton jButtonREINICIARU1;
    public javax.swing.JProgressBar jProgressBarUNIDAD1;
    // End of variables declaration//GEN-END:variables
}
